const data = [
  {
    id: 1,
    first_name: "Anselm",
    last_name: "Redington",
    email: "aredington0@dropbox.com",
    phone: "62(214)762-7571",
    country: "Indonesia",
    city: "Riit",
    address: "2342 Granby Drive",
    status: false,
    salary: "$4725.26",
    teams: "Consumer Services",
  },
  {
    id: 2,
    first_name: "Britni",
    last_name: "Wyard",
    email: "bwyard1@altervista.org",
    phone: "62(940)898-8148",
    country: "Indonesia",
    city: "Bakung Utara",
    address: "6493 Mitchell Road",
    status: false,
    salary: "$1936.49",
    teams: "n/a",
  },
  {
    id: 3,
    first_name: "Amata",
    last_name: "Billyeald",
    email: "abillyeald2@jalbum.net",
    phone: "33(659)113-2228",
    country: "France",
    city: "Vitry-sur-Seine",
    address: "2692 Erie Pass",
    status: true,
    salary: "$1742.44",
    teams: "Consumer Durables",
  },
  {
    id: 4,
    first_name: "Sven",
    last_name: "Buckston",
    email: "sbuckston3@squidoo.com",
    phone: "30(336)502-2683",
    country: "Greece",
    city: "Pánormos",
    address: "37 Sunfield Terrace",
    status: false,
    salary: "$2874.29",
    teams: "Consumer Non-Durables",
  },
  {
    id: 5,
    first_name: "Sonny",
    last_name: "Soro",
    email: "ssoro4@msn.com",
    phone: "234(910)230-3502",
    country: "Nigeria",
    city: "Ifo",
    address: "05937 Riverside Parkway",
    status: true,
    salary: "$2584.70",
    teams: "n/a",
  },
  {
    id: 6,
    first_name: "Tawsha",
    last_name: "Harm",
    email: "tharm5@about.com",
    phone: "7(191)981-5662",
    country: "Russia",
    city: "Nevel’",
    address: "63 Charing Cross Road",
    status: false,
    salary: "$1121.81",
    teams: "Public Utilities",
  },
  {
    id: 7,
    first_name: "Neile",
    last_name: "Dyshart",
    email: "ndyshart6@joomla.org",
    phone: "420(571)858-0532",
    country: "Czech Republic",
    city: "Žďár nad Sázavou",
    address: "9170 Crest Line Hill",
    status: false,
    salary: "$1443.74",
    teams: "Health Care",
  },
  {
    id: 8,
    first_name: "Suzanna",
    last_name: "Kayley",
    email: "skayley7@diigo.com",
    phone: "7(310)518-0987",
    country: "Russia",
    city: "Komsomol’sk",
    address: "12 Pepper Wood Place",
    status: false,
    salary: "$4051.05",
    teams: "Energy",
  },
  {
    id: 9,
    first_name: "Bambi",
    last_name: "Gladman",
    email: "bgladman8@youtube.com",
    phone: "63(705)417-2027",
    country: "Philippines",
    city: "Madrid",
    address: "2 Monica Pass",
    status: true,
    salary: "$2702.87",
    teams: "Health Care",
  },
  {
    id: 10,
    first_name: "Ellen",
    last_name: "Ardy",
    email: "eardy9@paypal.com",
    phone: "63(721)220-0035",
    country: "Philippines",
    city: "Esperanza",
    address: "272 Magdeline Junction",
    status: true,
    salary: "$3805.24",
    teams: "Consumer Services",
  },
  {
    id: 11,
    first_name: "Althea",
    last_name: "Bredes",
    email: "abredesa@com.com",
    phone: "420(614)563-4055",
    country: "Czech Republic",
    city: "Mikulovice",
    address: "20189 Banding Park",
    status: false,
    salary: "$2174.07",
    teams: "Capital Goods",
  },
  {
    id: 12,
    first_name: "Benji",
    last_name: "Pickworth",
    email: "bpickworthb@163.com",
    phone: "595(757)109-3919",
    country: "Paraguay",
    city: "Colonia Minga Porá",
    address: "5 Clyde Gallagher Avenue",
    status: false,
    salary: "$4139.87",
    teams: "n/a",
  },
  {
    id: 13,
    first_name: "Milzie",
    last_name: "Behrens",
    email: "mbehrensc@joomla.org",
    phone: "86(389)692-9620",
    country: "China",
    city: "Yuanyang",
    address: "96 Sheridan Crossing",
    status: false,
    salary: "$3681.80",
    teams: "Consumer Services",
  },
  {
    id: 14,
    first_name: "Quinn",
    last_name: "De Giorgi",
    email: "qdegiorgid@hugedomains.com",
    phone: "48(371)300-8451",
    country: "Poland",
    city: "Paprotnia",
    address: "6 Luster Center",
    status: false,
    salary: "$2865.76",
    teams: "Technology",
  },
  {
    id: 15,
    first_name: "Dierdre",
    last_name: "Chinn",
    email: "dchinne@angelfire.com",
    phone: "46(551)130-3520",
    country: "Sweden",
    city: "Uppsala",
    address: "7 Dexter Park",
    status: false,
    salary: "$4659.92",
    teams: "Consumer Services",
  },
  {
    id: 16,
    first_name: "Melantha",
    last_name: "Alger",
    email: "malgerf@alibaba.com",
    phone: "976(784)440-8397",
    country: "Mongolia",
    city: "Hüremt",
    address: "788 Dayton Crossing",
    status: false,
    salary: "$3391.28",
    teams: "Consumer Durables",
  },
  {
    id: 17,
    first_name: "Kariotta",
    last_name: "MacDonogh",
    email: "kmacdonoghg@java.com",
    phone: "33(279)221-0570",
    country: "France",
    city: "Dijon",
    address: "9069 Everett Road",
    status: true,
    salary: "$3654.85",
    teams: "Health Care",
  },
  {
    id: 18,
    first_name: "Tris",
    last_name: "Rickeard",
    email: "trickeardh@ted.com",
    phone: "1(916)905-9835",
    country: "United States",
    city: "Sacramento",
    address: "13 Hansons Way",
    status: true,
    salary: "$4102.86",
    teams: "Energy",
  },
  {
    id: 19,
    first_name: "Arlette",
    last_name: "McMichell",
    email: "amcmichelli@amazon.de",
    phone: "86(442)315-2847",
    country: "China",
    city: "Heshi",
    address: "47107 Moland Park",
    status: true,
    salary: "$4434.10",
    teams: "Basic Industries",
  },
  {
    id: 20,
    first_name: "Rooney",
    last_name: "Vedstra",
    email: "rvedstraj@cloudflare.com",
    phone: "93(501)439-1584",
    country: "Afghanistan",
    city: "Farah",
    address: "00596 2nd Center",
    status: true,
    salary: "$2920.09",
    teams: "Health Care",
  },
  {
    id: 21,
    first_name: "Lennard",
    last_name: "Carlesso",
    email: "lcarlessok@globo.com",
    phone: "48(283)745-0886",
    country: "Poland",
    city: "Sulęcin",
    address: "39 Lotheville Crossing",
    status: false,
    salary: "$3913.52",
    teams: "n/a",
  },
  {
    id: 22,
    first_name: "Mercie",
    last_name: "Grimsditch",
    email: "mgrimsditchl@berkeley.edu",
    phone: "66(842)381-4665",
    country: "Thailand",
    city: "Samut Sakhon",
    address: "2 Trailsway Hill",
    status: true,
    salary: "$4862.04",
    teams: "Capital Goods",
  },
  {
    id: 23,
    first_name: "Kelwin",
    last_name: "Epilet",
    email: "kepiletm@hud.gov",
    phone: "86(918)552-6219",
    country: "China",
    city: "Laiwu",
    address: "7754 Old Gate Center",
    status: true,
    salary: "$1972.22",
    teams: "Finance",
  },
  {
    id: 24,
    first_name: "Manuel",
    last_name: "Vankov",
    email: "mvankovn@mit.edu",
    phone: "31(880)649-1664",
    country: "Netherlands",
    city: "Brunssum",
    address: "935 Montana Way",
    status: false,
    salary: "$2078.82",
    teams: "Consumer Non-Durables",
  },
  {
    id: 25,
    first_name: "Leonora",
    last_name: "Kilshall",
    email: "lkilshallo@census.gov",
    phone: "86(444)200-4202",
    country: "China",
    city: "Yonghe",
    address: "1 Glendale Center",
    status: false,
    salary: "$1930.43",
    teams: "Consumer Services",
  },
  {
    id: 26,
    first_name: "Lainey",
    last_name: "Deschelle",
    email: "ldeschellep@foxnews.com",
    phone: "62(975)410-2818",
    country: "Indonesia",
    city: "Leran",
    address: "6204 Holmberg Place",
    status: true,
    salary: "$4320.83",
    teams: "Capital Goods",
  },
  {
    id: 27,
    first_name: "Chelsy",
    last_name: "MacAiline",
    email: "cmacailineq@amazonaws.com",
    phone: "55(228)393-4070",
    country: "Brazil",
    city: "Frederico Westphalen",
    address: "1286 Glendale Lane",
    status: true,
    salary: "$3119.50",
    teams: "Energy",
  },
  {
    id: 28,
    first_name: "Hodge",
    last_name: "Radden",
    email: "hraddenr@virginia.edu",
    phone: "420(956)914-4155",
    country: "Czech Republic",
    city: "Velké Pavlovice",
    address: "5316 Amoth Drive",
    status: true,
    salary: "$4818.06",
    teams: "Capital Goods",
  },
  {
    id: 29,
    first_name: "Fred",
    last_name: "Murtimer",
    email: "fmurtimers@washingtonpost.com",
    phone: "242(224)991-6925",
    country: "Democratic Republic of the Congo",
    city: "Lusambo",
    address: "1 Maryland Road",
    status: true,
    salary: "$2377.21",
    teams: "n/a",
  },
  {
    id: 30,
    first_name: "Skye",
    last_name: "Moulster",
    email: "smoulstert@drupal.org",
    phone: "48(198)237-4398",
    country: "Poland",
    city: "Koszęcin",
    address: "13 6th Road",
    status: true,
    salary: "$2913.90",
    teams: "Health Care",
  },
];


export default data